### ISSUE TITLE
OSSEC runtests documentation

### ISSUE THREAD

**Issue by ddpbsd** [ossec/ossec-docs#37]
I don't think we currently have any, or I can't find it. I think it'd be nice to have.

**Comment by nbuuck** [comment]
@ddpbsd Before I get too deep into this one, is this still something you'd like to see happen?

**Comment by ddpbsd** [comment]
I'm thinking just a quick "Here's how you run the tests" and maybe an example output of a failure and a successful run.
I think base python is enough, but understanding that it uses `ossec-logtest` from the install (or `/var/ossec`?), as well as the installed rules and decoders might be necessary

**Comment by nbuuck** [comment]
Working document to take notes and get a document structure established before bothering with a reStructuredText document.

https://docs.google.com/document/d/1pkksnpFDuF5qhH-3h4aMy6g6awM91kiyfGGxnX7dB9o/edit?usp=sharing

**Comment by nbuuck** [comment]
The test chain is pretty dependent on package versions more current than those available in the CentOS-7 repos. `check` moved away from a generic `ck_assert` function, preventing compile on CentOS (check package is 0.99.9) and perhaps even Fedora (package is 0.10.0). Trying to build `check` from source fails because of older versions of `autoconf` and `automake` in the Fedora/CentOS repos.

I'll probably deploy an Ubuntu instance for the purpose of completing this issue but it's probably worth noting - here and in the runtests doc being developed - that running tests on a non-Debian distro might not be supported. Granted, my use of CentOS may be peculiar or atypical for this project, but it does add some perspective to the platform limitations for developers.

**Comment by ddpbsd** [comment]
I think my initial intention with this issue was to document `contrib/ossec-testing/runtests.py` to test rules. Obviously I created the issue a long time ago, and promptly ignored it, so I could be mis-remembering.

But I think that would be a great starting point. Introduce the `runtests.py` script, and the tests files/format to hopefully encourage contributions. Documenting the build tests is a worth-while project, but I think the rule testing has a higher priority, and possibly more chance for ROI.

**Comment by nbuuck** [comment]
Ah, ok, that's great to know. Despite finding runtests.py, I made an assumption that `make run_tests` was somehow synonymous and that perhaps the Python script wasn't integral to testing yet. I'll redirect my efforts. Thanks!

**Comment by ddpbsd** [comment]
I think `make run_tests` ends up running `runtests.py`, but I'm not positive. It might just be something inside of the travis config. If it makes more sense, we can rename `runtests.py` to something like `rule-tests.py`

**Comment by nbuuck** [comment]
You're correct; I hadn't reviewed the build config for RULES=test yet, but that config doesn't run the Python script.

```
if [[ "${RULES}" == "test" ]]; then ( cd src/ && sudo make V=1 TARGET=server test-rules ) fi
( cd ../contrib/ossec-testing && sudo python runtests.py)
```

**Comment by nbuuck** [comment]
Getting back to this. Establishing a new build host with a more-modern distro so the testing dependencies can be satisfied.

**Comment by nbuuck** [comment]
@ddpbsd Looks like this is mostly already documented [here](https://ossec.github.io/docs/development/build/test-rules.html). This is actually a page you wrote in 681f57c. Since the `test-rules` target essentially just runs `runtests.py`, do you think further documentation is needed?

**Comment by ddpbsd** [comment]
Nope, guess not. I should probably try to remember what I wrote at some point. Thanks for finding that.
